name: Build and deploy Node.js project to Azure Function App - backendforvividtints

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'
  BUILD_FOLDER: 'build' # Change this to your actual build output folder if different

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies and build
        shell: pwsh
        run: |
          npm install
          npm run build --if-present

      - name: Verify build output
        run: dir ${{ env.BUILD_FOLDER }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: functionapp-build
          path: ${{ env.BUILD_FOLDER }}

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: functionapp-build

      - name: List downloaded files for debugging
        run: dir

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7CDE9471B8BE45A3B0F4091736C96679 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_89C07B73ADB749E7829A7AC6C772CC62 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FC12ADCB8BF140C5832DDB12A162240E }}

      - name: Deploy Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: 'backendforvividtints'
          package: './${{ env.BUILD_FOLDER }}'
